### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by GeoffreyPlitt** [oblador/react-native-collapsible#36]
I went into Example and did "npm install", do I need to do anything else?

$ react-native run-ios
module.js:327
    throw err;
    ^

Error: Cannot find module './packager/babelRegisterOnly'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/webfreelance10/react-native-collapsible/Example/node_modules/react-native/cli.js:11:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.
