### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `./config` from `node_modules/react-native-collapsible/Accordion.js`:

### ISSUE THREAD

**Issue by RitheanyChhem** [oblador/react-native-collapsible#408]
I've been struggling making a list inside Accordion Component, unfortunately I have got the issues below.

In react-native-collapsible release **1.6.0**

```
None of these files exist:
  * node_modules/react-native-collapsible/config(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * node_modules/react-native-collapsible/config/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
    at ModuleResolver.resolveDependency (/[PART_PROJECT]/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/[PART_PROJECT]/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/[PART_PROJECT]/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/[PART_PROJECT]/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at dependencies.map.result ([PART_PROJECT]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/[PART_PROJECT]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /[PART_PROJECT]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/[PART_PROJECT]/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

**Comment by RitheanyChhem** [comment]
I have no idea about.
I try to reverse  **"react-native-collapsible": "^1.5.3"**.
It works fine 👍

**Comment by calypsow777** [comment]
Have you tried clearing the cache with `npm start -- --reset-cache` ?

**Comment by ehtisham-ali-emumba** [comment]
someone should close this.

**Comment by ehtisham-ali-emumba** [comment]
> Have you tried clearing the cache with `npm start -- --reset-cache` ?

someone should close this, as following this solves for me.
